# Generated by Django 5.1.4 on 2025-01-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default_product.png', upload_to='product_images/'),
        ),
    ]
