# Generated by Django 5.0.6 on 2025-01-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_business_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
