# Generated by Django 5.1.4 on 2025-01-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_business_business_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(default='default_product.png', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='default_product.png', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default='default_product.png', upload_to='product_images/'),
        ),
    ]
