# Generated by Django 5.0.6 on 2025-02-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_order_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
