# Generated by Django 5.1.4 on 2025-02-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
