# Generated by Django 5.0.6 on 2025-03-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
