# Generated by Django 5.0.6 on 2025-03-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
