# Generated by Django 5.0.6 on 2025-03-17 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(default='default_product.png', null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='default_product.png', null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default='default_product.png', null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(default='default_product.png', null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image5',
            field=models.ImageField(default='default_product.png', null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
