# Generated by Django 5.0.6 on 2025-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_measurement',
            field=models.CharField(choices=[('g', 'Per Gram'), ('piece', 'Per Piece'), ('pack', 'Per Pack'), ('liter', 'Per Liter'), ('kilo', 'Per Kilo')], default='Per Kilo', max_length=10),
        ),
    ]
