# Generated by Django 5.0.6 on 2025-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_product_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_measurement',
            field=models.CharField(choices=[('Kilo', 'Per Kilo'), ('Gram', 'Per Gram'), ('Kiece', 'Per Piece'), ('Pack', 'Per Pack'), ('Liter', 'Per Liter')], default='Per Kilo', max_length=10),
        ),
    ]
