# Generated by Django 5.0.6 on 2025-03-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_product_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image5',
        ),
    ]
