# Generated by Django 5.0.6 on 2025-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_product_product_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(default='default_product.jpg', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='default_product.jpg', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(default='default_product.jpg', null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(default='default_product.jpg', null=True, upload_to='product_images/'),
        ),
    ]
