# Generated by Django 5.0.6 on 2025-03-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
