# Generated by Django 5.0.6 on 2025-03-20 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_notification_id_alter_order_id_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
