# Generated by Django 5.0.6 on 2025-03-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_business_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='create_at',
        ),
    ]
