# Generated by Django 5.0.6 on 2025-03-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_remove_business_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
