# Generated by Django 5.0.6 on 2025-08-03 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('seller_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('evidence_image', models.ImageField(upload_to='evidence_images/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
