# Generated by Django 5.0.6 on 2025-12-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_sellerreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(default='default_business_logo.png', upload_to='business_logo/'),
        ),
    ]
