# Generated by Django 5.0.6 on 2026-01-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_business_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_description',
            field=models.CharField(max_length=255),
        ),
    ]
