# Generated by Django 5.0.6 on 2025-04-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
